#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 16 20:00:57 2021

@author: franek
"""

import webbrowser, sys, pyperclip
if len(sys.argv) > 1:
    # Get address from command line.
    address = ' '.join(sys.argv[1:])
    
else:
    address = pyperclip.paste()

webbrowser.open('https://www.google.com/maps/place/' + address)

